[package]
org = "ballerina"
name = "config"
version = "@toml.version@"
[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "os"
version = "@stdlib.os.version@"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "@stdlib.stringutils.version@"

[[platform.java11.dependency]]
path = "../config-native/build/libs/config-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "config"
version = "@project.version@"
