[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/system" = "@stdlib.system.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "config"
    version = "@project.version@"
    path = "../config-native/build/libs/config-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["config"]
