[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "config"
    version = "1.0.0-SNAPSHOT"
    path = "../config-native/build/libs/config-native-1.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["config-api"]
